apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  annotations:
    client.knative.dev/user-image: gcr.io/ln-sherlock/stac-api:latest
  labels:
    cloud.googleapis.com/location: us-central1
  name: sherlock
  namespace: '18072996206'
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/maxScale: '1000'
        run.googleapis.com/client-name: cloud-console
        run.googleapis.com/cloudsql-instances: ln-sherlock:northamerica-northeast1:sherlock-stac-data
      name: sherlock-00001-fus
    spec:
      containerConcurrency: 80
      containers:
      - image: gcr.io/ln-sherlock/stac-api:latest
        ports:
        - containerPort: 8080
        resources:
          limits:
            cpu: 2000m
            memory: 1024Mi
      serviceAccountName: 18072996206-compute@developer.gserviceaccount.com
      timeoutSeconds: 300
  traffic:
  - latestRevision: true
    percent: 100
